name: custom_text_form_field_plus
description: Custom Text Form Field Plus - A Customizable Text Input Widget with Validation for Flutter
version: 0.0.5
repository: https://github.com/Dharti1623/CustomTextFormFieldPlus
homepage: https://github.com/Dharti1623

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.custom_text_form_field_plus
        pluginClass: CustomTextFormFieldPlusPlugin
      ios:
        pluginClass: CustomTextFormFieldPlusPlugin
      linux:
        pluginClass: CustomTextFormFieldPlusPlugin
      macos:
        pluginClass: CustomTextFormFieldPlusPlugin
      windows:
        pluginClass: CustomTextFormFieldPlusPluginCApi
      web:
        pluginClass: CustomTextFormFieldPlusWeb
        fileName: custom_text_form_field_plus_web.dart
